# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/Test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/Test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/Test/CMakeFiles /workspaces/Test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/Test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named X2Modern

# Build rule for target.
X2Modern: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 X2Modern
.PHONY : X2Modern

# fast build rule for target.
X2Modern/fast:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/build
.PHONY : X2Modern/fast

#=============================================================================
# Target rules for targets named X2Modern_autogen

# Build rule for target.
X2Modern_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 X2Modern_autogen
.PHONY : X2Modern_autogen

# fast build rule for target.
X2Modern_autogen/fast:
	$(MAKE) -f CMakeFiles/X2Modern_autogen.dir/build.make CMakeFiles/X2Modern_autogen.dir/build
.PHONY : X2Modern_autogen/fast

X2Modern_autogen/mocs_compilation.o: X2Modern_autogen/mocs_compilation.cpp.o

.PHONY : X2Modern_autogen/mocs_compilation.o

# target to build an object file
X2Modern_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/X2Modern_autogen/mocs_compilation.cpp.o
.PHONY : X2Modern_autogen/mocs_compilation.cpp.o

X2Modern_autogen/mocs_compilation.i: X2Modern_autogen/mocs_compilation.cpp.i

.PHONY : X2Modern_autogen/mocs_compilation.i

# target to preprocess a source file
X2Modern_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/X2Modern_autogen/mocs_compilation.cpp.i
.PHONY : X2Modern_autogen/mocs_compilation.cpp.i

X2Modern_autogen/mocs_compilation.s: X2Modern_autogen/mocs_compilation.cpp.s

.PHONY : X2Modern_autogen/mocs_compilation.s

# target to generate assembly for a file
X2Modern_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/X2Modern_autogen/mocs_compilation.cpp.s
.PHONY : X2Modern_autogen/mocs_compilation.cpp.s

src/account_manager.o: src/account_manager.cpp.o

.PHONY : src/account_manager.o

# target to build an object file
src/account_manager.cpp.o:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/account_manager.cpp.o
.PHONY : src/account_manager.cpp.o

src/account_manager.i: src/account_manager.cpp.i

.PHONY : src/account_manager.i

# target to preprocess a source file
src/account_manager.cpp.i:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/account_manager.cpp.i
.PHONY : src/account_manager.cpp.i

src/account_manager.s: src/account_manager.cpp.s

.PHONY : src/account_manager.s

# target to generate assembly for a file
src/account_manager.cpp.s:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/account_manager.cpp.s
.PHONY : src/account_manager.cpp.s

src/api_manager.o: src/api_manager.cpp.o

.PHONY : src/api_manager.o

# target to build an object file
src/api_manager.cpp.o:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/api_manager.cpp.o
.PHONY : src/api_manager.cpp.o

src/api_manager.i: src/api_manager.cpp.i

.PHONY : src/api_manager.i

# target to preprocess a source file
src/api_manager.cpp.i:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/api_manager.cpp.i
.PHONY : src/api_manager.cpp.i

src/api_manager.s: src/api_manager.cpp.s

.PHONY : src/api_manager.s

# target to generate assembly for a file
src/api_manager.cpp.s:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/api_manager.cpp.s
.PHONY : src/api_manager.cpp.s

src/bot_worker.o: src/bot_worker.cpp.o

.PHONY : src/bot_worker.o

# target to build an object file
src/bot_worker.cpp.o:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/bot_worker.cpp.o
.PHONY : src/bot_worker.cpp.o

src/bot_worker.i: src/bot_worker.cpp.i

.PHONY : src/bot_worker.i

# target to preprocess a source file
src/bot_worker.cpp.i:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/bot_worker.cpp.i
.PHONY : src/bot_worker.cpp.i

src/bot_worker.s: src/bot_worker.cpp.s

.PHONY : src/bot_worker.s

# target to generate assembly for a file
src/bot_worker.cpp.s:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/bot_worker.cpp.s
.PHONY : src/bot_worker.cpp.s

src/database_manager.o: src/database_manager.cpp.o

.PHONY : src/database_manager.o

# target to build an object file
src/database_manager.cpp.o:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/database_manager.cpp.o
.PHONY : src/database_manager.cpp.o

src/database_manager.i: src/database_manager.cpp.i

.PHONY : src/database_manager.i

# target to preprocess a source file
src/database_manager.cpp.i:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/database_manager.cpp.i
.PHONY : src/database_manager.cpp.i

src/database_manager.s: src/database_manager.cpp.s

.PHONY : src/database_manager.s

# target to generate assembly for a file
src/database_manager.cpp.s:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/database_manager.cpp.s
.PHONY : src/database_manager.cpp.s

src/log_manager.o: src/log_manager.cpp.o

.PHONY : src/log_manager.o

# target to build an object file
src/log_manager.cpp.o:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/log_manager.cpp.o
.PHONY : src/log_manager.cpp.o

src/log_manager.i: src/log_manager.cpp.i

.PHONY : src/log_manager.i

# target to preprocess a source file
src/log_manager.cpp.i:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/log_manager.cpp.i
.PHONY : src/log_manager.cpp.i

src/log_manager.s: src/log_manager.cpp.s

.PHONY : src/log_manager.s

# target to generate assembly for a file
src/log_manager.cpp.s:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/log_manager.cpp.s
.PHONY : src/log_manager.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/twitter_bot.o: src/twitter_bot.cpp.o

.PHONY : src/twitter_bot.o

# target to build an object file
src/twitter_bot.cpp.o:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/twitter_bot.cpp.o
.PHONY : src/twitter_bot.cpp.o

src/twitter_bot.i: src/twitter_bot.cpp.i

.PHONY : src/twitter_bot.i

# target to preprocess a source file
src/twitter_bot.cpp.i:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/twitter_bot.cpp.i
.PHONY : src/twitter_bot.cpp.i

src/twitter_bot.s: src/twitter_bot.cpp.s

.PHONY : src/twitter_bot.s

# target to generate assembly for a file
src/twitter_bot.cpp.s:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/twitter_bot.cpp.s
.PHONY : src/twitter_bot.cpp.s

src/twitter_bot_gui.o: src/twitter_bot_gui.cpp.o

.PHONY : src/twitter_bot_gui.o

# target to build an object file
src/twitter_bot_gui.cpp.o:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/twitter_bot_gui.cpp.o
.PHONY : src/twitter_bot_gui.cpp.o

src/twitter_bot_gui.i: src/twitter_bot_gui.cpp.i

.PHONY : src/twitter_bot_gui.i

# target to preprocess a source file
src/twitter_bot_gui.cpp.i:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/twitter_bot_gui.cpp.i
.PHONY : src/twitter_bot_gui.cpp.i

src/twitter_bot_gui.s: src/twitter_bot_gui.cpp.s

.PHONY : src/twitter_bot_gui.s

# target to generate assembly for a file
src/twitter_bot_gui.cpp.s:
	$(MAKE) -f CMakeFiles/X2Modern.dir/build.make CMakeFiles/X2Modern.dir/src/twitter_bot_gui.cpp.s
.PHONY : src/twitter_bot_gui.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... X2Modern"
	@echo "... X2Modern_autogen"
	@echo "... X2Modern_autogen/mocs_compilation.o"
	@echo "... X2Modern_autogen/mocs_compilation.i"
	@echo "... X2Modern_autogen/mocs_compilation.s"
	@echo "... src/account_manager.o"
	@echo "... src/account_manager.i"
	@echo "... src/account_manager.s"
	@echo "... src/api_manager.o"
	@echo "... src/api_manager.i"
	@echo "... src/api_manager.s"
	@echo "... src/bot_worker.o"
	@echo "... src/bot_worker.i"
	@echo "... src/bot_worker.s"
	@echo "... src/database_manager.o"
	@echo "... src/database_manager.i"
	@echo "... src/database_manager.s"
	@echo "... src/log_manager.o"
	@echo "... src/log_manager.i"
	@echo "... src/log_manager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/twitter_bot.o"
	@echo "... src/twitter_bot.i"
	@echo "... src/twitter_bot.s"
	@echo "... src/twitter_bot_gui.o"
	@echo "... src/twitter_bot_gui.i"
	@echo "... src/twitter_bot_gui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

